### ISSUE TITLE
Keep discussion posts in database

### ISSUE THREAD

**Issue by bnbcfyh** [bnbcfyh/cmpe352-2021-repeat-project#4]
The discussion posts are held in literal strings where each comment is separated by "#", in [event.py](https://github.com/bnbcfyh/cmpe352-2021-repeat-project/blob/master/practice-app/website/api/event.py).

This needs to be changed because:
-  This structure is against the logic of database.
-  There might be some problems when the user's post include the "#" character in it.

**Comment by suzan-uskudarli** [comment]
So how should it be stored? The description should say what to do

**Comment by bnbcfyh** [comment]
> So how should it be stored? The description should say what to do

First, I need to understand the details of the implementation to be able to provide a better description. I now opened an issue concerning this and it can be found [here](https://github.com/bnbcfyh/cmpe352-2021-repeat-project/issues/6).

However, as a more detailed description for this issue on what to do, it can be stated that there shall be changes on [models.py](https://github.com/bnbcfyh/cmpe352-2021-repeat-project/blob/master/practice-app/website/models.py) and [event.py](https://github.com/bnbcfyh/cmpe352-2021-repeat-project/blob/master/practice-app/website/api/event.py). These updates will change the way the data is stored. Instead of keeping them in literal strings, the data will be kept in a table and this table of comments will be joint to the table of discussion posts. As I said, more details will be provided on how to do it on SQLAlchemy as I complete my research.

**Comment by bnbcfyh** [comment]
I am currently working on the implementation and the research is done.

The things that are supposed to be changed are mentioned in that issue, on [this comment](https://github.com/bnbcfyh/cmpe352-2021-repeat-project/issues/6#issuecomment-902003154). As shown there, now I shall complete the other two changes listed there.

**Comment by bnbcfyh** [comment]
The implementations are made, pushed and a pull request has been created. The relevant pull request can be reviewed [here](https://github.com/bnbcfyh/cmpe352-2021-repeat-project/pull/11) and can be merged after the consideration.

**Comment by bnbcfyh** [comment]
Reviewed and merged. This issue can be closed now.
